- pom.xml
- src/main/java/neqsim/processSimulation/processEquipment/compressor/Compressor.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChart.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartAlternativeMapLookup.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartInterface.java
- Made interface for implementing different compressor chart classes
- Implemented CompressorChartAlternativeMapLookup which uses double interpolation with Fan laws to navigate the compressor map given flow and speed
- Implemented a constructor in the Compressor Class to support the changes
- Added a real test case in both compressor chart classes
- Temporarily changed the Fan law correction code in CompressorChart class (created a bug for unequal number of points in different compressor curves in the map)
> New compressor chart type

- src/main/java/neqsim/processSimulation/measurementDevice/MultiPhaseMeter.java
- src/main/java/neqsim/processSimulation/processEquipment/util/GORfitter.java
typos and returned pressure instead of temperature
> bugfix: get temperature

- src/main/java/neqsim/processSimulation/processEquipment/separator/Separator.java
- src/main/java/neqsim/processSimulation/processSystem/ProcessSystem.java
- src/test/java/neqsim/processSimulation/processSystem/ProcessSystemTest.java
> refact: ProcessSystem add checks for duplicates

- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartAlternativeMapLookup.java
- src/main/java/neqsim/thermo/characterization/LumpingModel.java
- src/main/java/neqsim/thermo/component/Component.java
- src/main/java/neqsim/thermo/phase/Phase.java
- src/main/java/neqsim/thermo/system/SystemInterface.java
- src/main/java/neqsim/thermo/system/SystemThermo.java
- src/main/java/neqsim/util/exception/NotInitializedException.java
- src/test/java/neqsim/thermo/system/SystemThermoSetMolarCompositionTest.java
Added testcases
Some docfixes
feat: included logged error message in neqsimexceptions
bugfix: fractionOfHeavyEnd not set throws notinitializedexception
> Created tests for setMolarComposition

- src/main/java/neqsim/processSimulation/processEquipment/powerGeneration/GasTurbine.java
- src/main/java/neqsim/thermo/Fluid.java
- src/test/java/neqsim/processSimulation/processEquipment/powerGeneration/GasTurbineTest.java
> refact: gasturbine created test from main-method

- .gitignore
- .mvn/wrapper/maven-wrapper.properties
- README.md
- mvnw
- mvnw.cmd
>  Added in apache maven wrapper

- pom.xml
compiling in maven now requires jdk 11 or higher
> chore: update plugin versions

- pom.xml
https://medium.com/@kkdthunlshd/publish-github-project-in-maven-central-repository-bdf0e5aa2b82
> use central maven repo

- src/main/java/neqsim/physicalProperties/physicalPropertyMethods/commonPhasePhysicalProperties/viscosity/PFCTViscosityMethodHeavyOil.java
- src/test/java/neqsim/physicalProperties/physicalPropertyMethods/commonPhasePhysicalProperties/viscosity/FrictionTheoryViscosityMethodTest.java
- src/test/java/neqsim/physicalProperties/physicalPropertyMethods/commonPhasePhysicalProperties/viscosity/PFCTViscosityMethodTest.java
viscosity of hydrogen returns NaN. Fix method.
Ref: https://github.com/equinor/neqsimhome/issues/3
> hydrogen viscosity update

- src/main/java/neqsim/thermodynamicOperations/ThermodynamicOperations.java
- src/test/java/neqsim/thermodynamicOperations/ThermodynamicOperationsTest.java
refact: Introduced enum type FlashType
> bugfix: ThermodynamicOperations.flash missing call of TPFlash

- src/main/java/neqsim/processSimulation/processEquipment/TwoPortInterface.java
- src/main/java/neqsim/processSimulation/processEquipment/mixer/MixerInterface.java
- src/main/java/neqsim/processSimulation/processEquipment/util/Recycle.java
solve not checking for absolute distance, negative errors can fool the verification.
> Bugfix solve function of Recycle

- src/main/java/neqsim/chemicalReactions/chemicalReaction/ChemicalReactionList.java
- src/main/java/neqsim/fluidMechanics/flowSystem/FlowSystem.java
- src/main/java/neqsim/fluidMechanics/flowSystem/onePhaseFlowSystem/OnePhaseFlowSystem.java
- src/main/java/neqsim/fluidMechanics/flowSystem/twoPhaseFlowSystem/TwoPhaseFlowSystem.java
- src/main/java/neqsim/processSimulation/measurementDevice/WellAllocator.java
- src/main/java/neqsim/processSimulation/processEquipment/pipeline/AdiabaticTwoPhasePipe.java
- src/main/java/neqsim/processSimulation/processEquipment/pipeline/Pipeline.java
- src/test/java/neqsim/chemicalReactions/chemicalReaction/ChemicalReactionListTest.java
- src/test/java/neqsim/processSimulation/processEquipment/pipeline/AdiabaticTwoPhasePipeTest.java
> chore: remove unused main methods

- src/main/java/neqsim/processSimulation/measurementDevice/CricondenbarAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/HydrateEquilibriumTemperatureAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/LevelTransmitter.java
- src/main/java/neqsim/processSimulation/measurementDevice/MeasurementDeviceBaseClass.java
- src/main/java/neqsim/processSimulation/measurementDevice/MeasurementDeviceInterface.java
- src/main/java/neqsim/processSimulation/measurementDevice/MolarMassAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/MultiPhaseMeter.java
- src/main/java/neqsim/processSimulation/measurementDevice/NMVOCAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/PressureTransmitter.java
- src/main/java/neqsim/processSimulation/measurementDevice/StreamMeasurementDeviceBaseClass.java
- src/main/java/neqsim/processSimulation/measurementDevice/TemperatureTransmitter.java
- src/main/java/neqsim/processSimulation/measurementDevice/VolumeFlowTransmitter.java
- src/main/java/neqsim/processSimulation/measurementDevice/WaterContentAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/WaterDewPointAnalyser.java
- src/main/java/neqsim/processSimulation/measurementDevice/WellAllocator.java
- src/main/java/neqsim/processSimulation/measurementDevice/pHProbe.java
- src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/SevereSlugAnalyser.java
- src/main/java/neqsim/processSimulation/processEquipment/separator/Separator.java
- src/main/java/neqsim/processSimulation/processEquipment/util/GORfitter.java
- src/main/java/neqsim/processSimulation/util/monitor/MPMResponse.java
- src/main/java/neqsim/processSimulation/util/monitor/WellAllocatorResponse.java
- src/main/java/neqsim/util/NamedBaseClass.java
- src/test/java/neqsim/processSimulation/measurementDevice/MultiPhaseMeterTest.java
- src/test/java/neqsim/processSimulation/measurementDevice/nmVOCTest.java
- src/test/java/neqsim/processSimulation/measurementDevice/pHProbeTest.java
- src/test/java/neqsim/processSimulation/processEquipment/separator/SeparatorTest.java
- src/test/java/neqsim/processSimulation/processEquipment/util/GORfitterTest.java
- src/test/java/neqsim/processSimulation/processSystem/ProcessSystemRunTransientTest.java
- src/test/java/neqsim/processSimulation/util/example/TestTransientFlow.java
refact: measurementdevice classes
> refact: create StreamMeasurementDeviceBaseClass

- pom.xml
- pomJava8.xml
Plan for a new release when remaining issues have been closed:
https://github.com/equinor/neqsim/milestone/8
> create release 2.5.0

- .gitignore
- src/main/java/neqsim/util/database/NeqSimDataBase.java
- src/test/java/neqsim/util/database/NeqSimDataBaseTest.java
Had issues where testing failed and running main-methods failed due to not finding the csv-files.
> refact: robustify h2 db init and updates from csv

- pom.xml
- pomJava8.xml
ref: https://maven.apache.org/guides/mini/guide-naming-conventions.html
> chore: maven groupid shall be com.equinor.neqsim

- src/main/java/neqsim/PVTsimulation/simulation/ConstantVolumeDepletion.java
- src/main/java/neqsim/PVTsimulation/simulation/DensitySim.java
- src/main/java/neqsim/PVTsimulation/simulation/DifferentialLiberation.java
- src/main/java/neqsim/PVTsimulation/simulation/SaturationPressure.java
- src/main/java/neqsim/PVTsimulation/simulation/SaturationTemperature.java
- src/main/java/neqsim/PVTsimulation/simulation/SlimTubeSim.java
- src/main/java/neqsim/PVTsimulation/simulation/ViscositySim.java
- src/main/java/neqsim/chemicalReactions/chemicalEquilibriaum/ChemicalEquilibrium.java
- src/main/java/neqsim/log4j2.properties
- src/main/java/neqsim/processSimulation/processEquipment/splitter/Splitter.java
- src/main/java/neqsim/processSimulation/processEquipment/util/Calculator.java
- src/main/java/neqsim/thermo/component/Component.java
- src/main/java/neqsim/thermo/phase/Phase.java
- src/main/java/neqsim/thermo/system/SystemThermo.java
- src/main/java/neqsim/thermodynamicOperations/flashOps/Flash.java
- src/main/java/neqsim/util/database/NeqSimDataBase.java
- src/test/java/neqsim/PVTsimulation/simulation/ConstantMassExpansionTest.java
- src/test/java/neqsim/PVTsimulation/simulation/ConstantVolumeDepletionTest.java
- src/test/java/neqsim/PVTsimulation/simulation/DensitySimTest.java
- src/test/java/neqsim/PVTsimulation/simulation/DifferentialLiberationTest.java
- src/test/java/neqsim/PVTsimulation/simulation/SeparatorTestTest.java
- src/test/java/neqsim/PVTsimulation/simulation/SlimTubeSimTest.java
- src/test/java/neqsim/PVTsimulation/simulation/ViscositySimTest.java
- src/test/java/neqsim/PVTsimulation/simulation/WaxFractionSimTest.java
- src/test/java/neqsim/processSimulation/processEquipment/splitter/ComponentSplitterTest.java
- src/test/java/neqsim/thermodynamicOperations/flashOps/TPFlashTestHighTemp.java
- src/test/java/neqsim/thermodynamicOperations/flashOps/WaxFlashTest.java
This bug is related to som PVT simulations are failing in NeqSim release 2.5.1.
https://colab.research.google.com/github/EvenSol/NeqSim-Colab/blob/master/notebooks/PVT/PVTreports.ipynb
> work on difflib bug

- src/main/java/neqsim/PVTsimulation/simulation/SlimTubeSim.java
- src/main/java/neqsim/processSimulation/measurementDevice/CombustionEmissionsCalculator.java
- src/test/java/neqsim/processSimulation/measurementDevice/CombustionEmissionsCalculatorTest.java
Estimate CO2 emissions from combustion of a stream
> add CombustionEmissionsCalculator

- src/main/java/neqsim/PVTsimulation/simulation/DifferentialLiberation.java
- src/main/java/neqsim/PVTsimulation/simulation/SlimTubeSim.java
fix failed test in difflib calc
> fix failed test difflib test

- src/main/java/neqsim/log4j2.properties
- src/main/java/neqsim/processSimulation/processEquipment/reservoir/SimpleReservoir.java
- src/test/java/neqsim/processSimulation/processEquipment/reservoir/SimpleReservoirTest.java
work on reservoir simulation model
> Update reservoir simulation model

- src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java
- src/test/java/neqsim/processSimulation/processEquipment/pipeline/BeggsAndBrillsPipeTest.java
Improvements:
Fixed the bug related to densities units.
Added unit tests to validate the code changes.
Added more output variables. 
Angle (or elevation or length are now calculated based on two other parameters)
> Pipe Beggs and Brills 

- src/main/java/neqsim/processSimulation/costEstimation/CostEstimateBaseClass.java
- src/main/java/neqsim/processSimulation/mechanicalDesign/SystemMechanicalDesign.java
- src/main/java/neqsim/processSimulation/mechanicalDesign/pipeline/PipelineMechanicalDesign.java
- src/main/java/neqsim/processSimulation/mechanicalDesign/valve/ValveMechanicalDesign.java
- src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentBaseClass.java
- src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentInterface.java
- src/main/java/neqsim/processSimulation/processEquipment/distillation/DistillationColumn.java
- src/main/java/neqsim/processSimulation/processEquipment/manifold/Manifold.java
- src/main/java/neqsim/processSimulation/processEquipment/pipeline/Pipeline.java
- src/main/java/neqsim/processSimulation/processEquipment/separator/Separator.java
- src/main/java/neqsim/processSimulation/processEquipment/valve/ThrottlingValve.java
- src/main/java/neqsim/processSimulation/processSystem/ProcessSystem.java
- src/main/java/neqsim/processSimulation/processSystem/processModules/SeparationTrainModule.java
- src/main/java/neqsim/processSimulation/processSystem/processModules/SeparationTrainModuleSimple.java
- src/test/java/neqsim/processSimulation/mechanicalDesign/SystemMechanicalDesignTest.java
- src/test/java/neqsim/processSimulation/util/example/OffshoreProcess3.java
- src/test/java/neqsim/processSimulation/util/example/simpleGasScrubber.java
- src/test/java/neqsim/processSimulation/util/example/testGasScrubber.java
The automated mechanical design calculations needs to be updated. Tests need to be added, and design methods and data for more equipment need to be added.
The calculations should give a rough weight and volume estimation of a full process.
> update mechanical design simulations

- src/main/java/neqsim/standards/gasQuality/Standard_ISO15403.java
- src/test/java/neqsim/standards/gasQuality/Standard_ISO15403Test.java
add ISO15403 for methane number
https://www.iso.org/standard/44211.html
> added ISO15403

- src/main/java/neqsim/util/database/NeqSimDataBase.java
- src/test/java/neqsim/util/database/NeqSimDataBaseTest.java
Add method replace database table
> add replace database table and test

- pom.xml
- pomJava8.xml
> chore: release new version 2.5.7

- src/main/java/neqsim/processSimulation/processEquipment/distillation/DistillationColumn.java
- src/main/java/neqsim/thermodynamicOperations/ThermodynamicOperations.java
Improve stability of TEG process.
> fix stability of TEG process

- src/test/java/neqsim/fluidMechanics/flowSystem/twoPhaseFlowSystem/shipSystem/LNGshipTest.java
Added some simple tests to LNGShip. 
Mostly tests that it runs ok. Need further testing on results
> test: add LNGship unit tests

- src/main/java/neqsim/processSimulation/controllerDevice/ControllerDeviceBaseClass.java
- src/main/java/neqsim/processSimulation/controllerDevice/ControllerDeviceInterface.java
- src/main/java/neqsim/processSimulation/measurementDevice/CompressorMonitor.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/Compressor.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChart.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartAlternativeMapLookup.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartGenerator.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartInterface.java
- src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorInterface.java
- src/main/java/neqsim/processSimulation/processEquipment/heatExchanger/Heater.java
- src/main/java/neqsim/processSimulation/processEquipment/splitter/Splitter.java
- src/main/java/neqsim/processSimulation/processEquipment/util/SetPoint.java
- src/main/java/neqsim/processSimulation/processEquipment/valve/ThrottlingValve.java
- src/main/java/neqsim/processSimulation/util/monitor/CompressorResponse.java
- src/test/java/neqsim/processSimulation/processSystem/ProcessSystemRunTransientTest.java
Add dynamic calculations for compressors
> added compressor test and initial code

- src/main/java/neqsim/processSimulation/measurementDevice/MultiPhaseMeter.java
- src/main/java/neqsim/processSimulation/processEquipment/stream/Stream.java
- src/main/java/neqsim/processSimulation/processEquipment/util/GORfitter.java
- src/test/java/neqsim/processSimulation/processEquipment/util/GORfitterTest.java
Suggested bug fix:
Had to do when we create a stream from another stream (as we do for stream2). Then we set temperature and pressure on it - but it does not set it on the correct stream. Now this is fixed I hope.
> Bug  mpm returns incorrect value

- src/main/java/neqsim/processSimulation/measurementDevice/MultiPhaseMeter.java
- src/main/java/neqsim/processSimulation/processEquipment/stream/Stream.java
- src/main/java/neqsim/processSimulation/processEquipment/util/GORfitter.java
- src/test/java/neqsim/processSimulation/processEquipment/util/GORfitterTest.java
* bug: MPM returns incorrect value
* bug fix suggestion.
Bug had to do when we create a stream from another stream (as we do for stream2). Then we set temperature and pressure on it - but it does not set it on the correct stream
* added init properties
* bug fix
* update
* fix bug
* new fix
---------
> Bug  mpm returns incorrect value (#917)

- .devcontainer/devcontainer.json
- .vscode/settings.json
- checkstyle_neqsim.xml
chore: update checkstyle version
style: fix xml and json tab settings
> fix: update devcontainer.json to new format

- .github/workflows/maven_publish.yml
- pom.xml
Automatically publish releases to maven central repository
> feat: publish releases to maven central repository

- checkstyle_neqsim.xml
- pom.xml
remove unused/outdated parameters
> chore: add checkstyle plugin

- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/KTAViscosityMethodMod.java
Updated KTAMod to get higher accuracy at high temperatures.
> KTAmod update for higher temperatures

- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/KTAViscosityMethod.java
- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/KTAViscosityMethodMod.java
- src/main/java/neqsim/thermo/component/ComponentGERG2008Eos.java
- src/main/java/neqsim/thermo/component/ComponentLeachmanEos.java
- src/main/java/neqsim/thermo/phase/Phase.java
- src/main/java/neqsim/thermo/phase/PhaseGERG2008Eos.java
- src/main/java/neqsim/thermo/phase/PhaseInterface.java
- src/main/java/neqsim/thermo/phase/PhaseLeachmanEos.java
- src/main/java/neqsim/thermo/system/SystemGERG2008Eos.java
- src/main/java/neqsim/thermo/system/SystemLeachmanEos.java
- src/main/java/neqsim/thermo/util/Vega/NeqSimVega.java
- src/main/java/neqsim/thermo/util/Vega/Vega.java
- src/main/java/neqsim/thermo/util/gerg/NeqSimGERG2008.java
- src/main/java/neqsim/thermo/util/leachman/NeqSimLeachman.java
- src/test/java/neqsim/thermo/util/Vega/VegaTest.java
- src/test/java/neqsim/thermo/util/gerg/GERG2008Test.java
- src/test/java/neqsim/thermo/util/leachman/LeachmanTest.java
Added system, phase and components class for Leachman, Vega and GERG2008. 
Note! The GERG2008 EOS is nott fully implemented and errors might occur for complex systems
> Added Leachman, Vega and GERG2008 Systems

- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/LBCViscosityMethod.java
- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MethaneViscosityMethod.java
- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MuznyModViscosityMethod.java
- src/main/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MuznyViscosityMethod.java
- src/main/java/neqsim/physicalproperties/system/PhysicalProperties.java
- src/test/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/LBCViscosityMethodTest.java
- src/test/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MethaneViscosityMethodTest.java
- src/test/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MuznyModViscosityMethodTest.java
- src/test/java/neqsim/physicalproperties/methods/commonphasephysicalproperties/viscosity/MuznyViscosityMethodTest.java
A couple of new models, and some chenges on LBC model for better accuracy for pure methane. The Muzny model is for pure hydrogen, and MuznyMod is more accurate.
> A couple of new models, and some chenges on LBC model for better accuracy for pure methane.

- src/main/java/neqsim/process/equipment/ProcessEquipmentInterface.java
- src/main/java/neqsim/process/equipment/stream/StreamInterface.java
- src/main/java/neqsim/thermo/component/Component.java
- src/main/java/neqsim/thermo/component/ComponentBWRS.java
- src/main/java/neqsim/thermo/component/ComponentEos.java
- src/main/java/neqsim/thermo/component/attractiveeosterm/AttractiveTermBaseClass.java
- src/main/java/neqsim/thermo/mixingrule/EosMixingRuleHandler.java
- src/main/java/neqsim/thermo/phase/Phase.java
- src/main/java/neqsim/thermo/phase/PhaseEos.java
- src/main/java/neqsim/thermo/system/SystemEos.java
- src/main/java/neqsim/thermo/system/SystemPrEos.java
- src/main/java/neqsim/thermo/system/SystemThermo.java
- src/main/java/neqsim/thermodynamicoperations/flashops/TPflash.java
- src/test/java/neqsim/thermo/system/SystemThermoTest.java
> feat: implement and test equality comparators

- src/main/java/neqsim/util/generator/PropertyGenerator.java
> fix: use Cv instead of Cp in property generator

- src/main/java/neqsim/util/generator/PropertyGenerator.java
> Revert "fix: use Cv instead of Cp in property generator"

- src/main/java/neqsim/process/equipment/heatexchanger/Heater.java
- src/main/java/neqsim/process/equipment/mixer/Mixer.java
- src/main/java/neqsim/process/equipment/mixer/StaticMixer.java
- src/main/java/neqsim/process/equipment/mixer/StaticNeqMixer.java
- src/main/java/neqsim/process/equipment/mixer/StaticPhaseMixer.java
- src/main/java/neqsim/process/equipment/pipeline/IncompressiblePipeFlow.java
- src/main/java/neqsim/process/equipment/pipeline/OnePhasePipeLine.java
- src/main/java/neqsim/process/equipment/pipeline/PipeBeggsAndBrills.java
- src/main/java/neqsim/process/equipment/pipeline/SimpleTPoutPipeline.java
- src/main/java/neqsim/process/equipment/separator/GasScrubberSimple.java
- src/main/java/neqsim/process/equipment/separator/Hydrocyclone.java
- src/main/java/neqsim/process/equipment/separator/NeqGasScrubber.java
- src/main/java/neqsim/process/equipment/separator/Separator.java
- src/main/java/neqsim/process/equipment/stream/EquilibriumStream.java
- src/main/java/neqsim/process/equipment/stream/IronIonSaturationStream.java
- src/main/java/neqsim/process/equipment/stream/NeqStream.java
- src/main/java/neqsim/process/equipment/stream/Stream.java
> always initProperties of unit operations

- src/main/java/neqsim/thermo/system/SystemInterface.java
- src/main/java/neqsim/thermo/system/SystemThermo.java
> add setComponentFlowRates

- src/main/java/neqsim/util/NeqSimLogging.java
- src/test/java/neqsim/util/NeqSimLoggingTest.java
Title: Enhance Global Logging Control for NeqSim Package
Description: This pull request introduces improvements to the NeqSimLogging utility class, enabling robust global logging control for all classes in the neqsim package using Log4j2. Key changes include:
Global Logging Control:
Added setGlobalLogging(String level) method to dynamically enable/disable logging and set logging levels for all neqsim classes and subpackages.
Ensured logging level changes propagate to all relevant loggers.
Reset Loggers:
Updated resetAllLoggers() method to reload logger configuration from the log4j2.properties file, ensuring default settings are restored.
Error Handling:
Added exception handling in resetAllLoggers() to log errors if the configuration file is missing or invalid.
Unit Tests:
Enhanced …
> change neqsim logging

- src/main/java/neqsim/process/equipment/compressor/CompressorChartAlternativeMapLookup.java
- src/main/java/neqsim/process/equipment/compressor/CompressorChartKhader2015.java
- src/test/java/neqsim/process/equipment/compressor/CompressorChartKhader2015Test.java
> bug fix comressor

- docs/wiki/distillation_column.md
- docs/wiki/index.md
- src/main/java/neqsim/process/equipment/distillation/DistillationColumn.java
- src/main/java/neqsim/thermodynamicoperations/ThermodynamicOperations.java
> various fixes

- src/main/java/neqsim/process/equipment/pipeline/PipeBeggsAndBrills.java
- src/test/java/neqsim/process/equipment/pipeline/PipeBeggsAndBrillsBoundaryTest.java
> beggs brill update?

- src/test/java/neqsim/process/equipment/pipeline/PipeBeggsAndBrillsBoundaryTest.java
> fix: test Pipe Beggs and Brills

- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing_IEC_60534.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ValveMechanicalDesign.java
- src/test/java/neqsim/process/equipment/valve/ThrottlingValveTest.java
> further update valve calcs

- src/main/java/neqsim/process/equipment/valve/ThrottlingValve.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizingInterface.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing_IEC_60534.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing_IEC_60534_full.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing_simple.java
- src/main/java/neqsim/process/mechanicaldesign/valve/LinearCharacteristic.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ValveCharacteristic.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ValveMechanicalDesign.java
- src/test/java/neqsim/process/equipment/valve/ThrottlingValveTest.java
- src/test/java/neqsim/process/mechanicaldesign/valve/ControlValveSizingTest.java
- src/test/java/neqsim/process/processmodel/ProcessSystemRunTransientTest.java
> update valve calc

- src/main/java/neqsim/process/equipment/compressor/BoundaryCurve.java
- src/main/java/neqsim/process/equipment/compressor/BoundaryCurveInterface.java
- src/main/java/neqsim/process/equipment/compressor/CompressorChartKhader2015.java
- src/main/java/neqsim/process/equipment/compressor/SafeSplineStoneWallCurve.java
- src/main/java/neqsim/process/equipment/compressor/SafeSplineSurgeCurve.java
- src/main/java/neqsim/process/equipment/compressor/StoneWallCurve.java
- src/main/java/neqsim/process/equipment/compressor/SurgeCurve.java
- src/test/java/neqsim/process/equipment/compressor/CompressorChartKhader2015Test.java
clean up surge and stone wall curve implementation
> clean up surge and stone wall curve implementation

- src/main/java/neqsim/thermodynamicoperations/flashops/TPmultiflash.java
check efect on reverting this modification in v 3.0.17
> update bug flash

- src/main/java/neqsim/process/equipment/valve/SafetyReliefValve.java
- src/test/java/neqsim/process/equipment/valve/SafetyReliefValveTest.java
> add safety valve implementation

- src/main/java/neqsim/blackoil/BlackOilConverter.java
- src/main/java/neqsim/blackoil/BlackOilFlash.java
- src/main/java/neqsim/blackoil/BlackOilFlashResult.java
- src/main/java/neqsim/blackoil/BlackOilPVTTable.java
- src/main/java/neqsim/blackoil/SystemBlackOil.java
- src/main/java/neqsim/blackoil/io/EclipseBlackOilImporter.java
- src/main/java/neqsim/process/equipment/blackoil/BlackOilSeparator.java
- src/test/java/neqsim/blackoil/SystemBlackOilTest.java
- src/test/java/neqsim/blackoil/io/EclipseBlackOilImporterTest.java
> Blackoil model

- src/main/java/neqsim/thermo/phase/PhaseBNS.java
> fix bug PhaseBNS

- src/main/java/neqsim/thermo/phase/Phase.java
- src/main/java/neqsim/thermo/system/SystemProperties.java
- src/main/java/neqsim/thermo/system/SystemThermo.java
- src/test/java/neqsim/thermo/system/SystemThermoTest.java
fix Cp and Cv conversion to field units
> updates conversion

- src/main/java/neqsim/util/unit/PressureUnit.java
- src/main/java/neqsim/util/unit/RateUnit.java
- src/main/java/neqsim/util/unit/TemperatureUnit.java
- src/test/java/neqsim/util/unit/PressureUnitTest.java
- src/test/java/neqsim/util/unit/TemperatureUnitTest.java
> updates in unit conversion

- src/main/java/neqsim/thermo/component/ComponentGERG2008Eos.java
- src/main/java/neqsim/thermo/phase/PhaseGERG2008Eos.java
- src/test/java/neqsim/thermo/phase/PhaseGERG2008EosTest.java
> update GERG2008 model

- src/main/java/neqsim/thermo/component/ComponentPCSAFT.java
- src/main/java/neqsim/thermo/phase/PhasePCSAFT.java
- src/test/java/neqsim/thermo/phase/PhasePCSAFTRahmatTest.java
> Update PC-SAFT EoS

- src/main/java/neqsim/process/equipment/compressor/Compressor.java
- src/main/java/neqsim/process/equipment/compressor/CompressorChart.java
- src/main/java/neqsim/process/equipment/compressor/CompressorChartAlternativeMapLookup.java
- src/main/java/neqsim/process/equipment/compressor/CompressorChartInterface.java
- src/test/java/neqsim/process/equipment/compressor/CompressorCapacityCheckTest.java
- src/test/java/neqsim/process/equipment/compressor/CompressorChartTest.java
check if compressor operates in valid area (within compressor curves)
> check compressor operation methods

- pom.xml
- pomJava21.xml
- pomJava8.xml
- src/main/java/neqsim/thermo/system/SystemBnsEos.java
- src/test/java/neqsim/thermo/system/SystemBnsEosParityTest.java
> bns update

- src/main/java/neqsim/thermo/component/ComponentEos.java
- src/main/java/neqsim/thermo/mixingrule/EosMixingRuleHandler.java
- src/main/java/neqsim/thermo/phase/PhaseCSPsrkEos.java
- src/main/java/neqsim/thermo/phase/PhaseElectrolyteCPA.java
- src/main/java/neqsim/thermo/phase/PhaseElectrolyteCPAOld.java
- src/main/java/neqsim/thermo/phase/PhaseEos.java
- src/main/java/neqsim/thermo/phase/PhasePCSAFT.java
- src/main/java/neqsim/thermo/phase/PhasePCSAFTRahmat.java
- src/main/java/neqsim/thermo/phase/PhasePCSAFTa.java
- src/main/java/neqsim/thermo/phase/PhaseSrkCPA.java
- src/main/java/neqsim/thermo/phase/PhaseUMRCPA.java
- src/test/java/neqsim/fluidmechanics/flowsystem/twophaseflowsystem/shipsystem/LNGshipTest.java
- src/test/java/neqsim/process/equipment/util/GORfitterTest.java
- src/test/java/neqsim/thermo/system/AcidTest.java
- src/test/java/neqsim/thermo/system/SystemBnsEosParityTest.java
> mixing rule update

- src/main/java/neqsim/process/equipment/compressor/Compressor.java
- src/main/java/neqsim/process/equipment/heatexchanger/HeatExchanger.java
- src/main/java/neqsim/process/equipment/valve/ThrottlingValve.java
- src/main/java/neqsim/process/mechanicaldesign/compressor/CompressorMechanicalDesign.java
- src/main/java/neqsim/process/mechanicaldesign/heatexchanger/HeatExchangerMechanicalDesign.java
- src/main/java/neqsim/process/mechanicaldesign/valve/ControlValveSizing.java
- src/test/java/neqsim/process/mechanicaldesign/compressor/CompressorMechanicalDesignTest.java
- src/test/java/neqsim/process/mechanicaldesign/heatexchanger/HeatExchangerMechanicalDesignTest.java
- src/test/java/neqsim/process/mechanicaldesign/valve/ValveMechanicalDesignTest.java
mechanical design of valves, compressors and heat exchangers
> mechanical design of valves, compressors and heat exchangers

- src/test/java/neqsim/process/controllerdevice/ProcessControlExampleTest.java
add a more advanced controll example
> add controll example

- src/main/java/neqsim/process/measurementdevice/MeasurementDeviceBaseClass.java
Avoid XStream reflection failures in Java 21
> Avoid XStream reflection failures in Java 21

- pom.xml
- pomJava21.xml
- pomJava8.xml
> chore: update neqsim

- src/main/java/neqsim/process/controllerdevice/ModelPredictiveController.java
- src/test/java/neqsim/process/controllerdevice/ModelPredictiveControllerTest.java
> Mpc controller

- src/main/java/neqsim/process/controllerdevice/ModelPredictiveController.java
- src/test/java/neqsim/process/controllerdevice/ModelPredictiveControllerTest.java
Extended ModelPredictiveController with receding/moving horizon estimation support, adding documentation, state tracking, configuration APIs, and integration into the single-input control loop so samples are recorded for online identification.
> MPC recording/moving horizon

- src/main/java/neqsim/process/equipment/util/Calculator.java
- src/test/java/neqsim/process/equipment/compressor/SafeSplineSurgeCurveTest.java
- src/test/java/neqsim/process/equipment/util/CalculatorAntiSurgeTest.java
> Updates graph
