src/main/java/neqsim/thermo/phase/PhaseInterface.java
src/main/java/neqsim/thermo/system/SystemProperties.java
src/main/java/neqsim/thermodynamicOperations/ThermodynamicOperations.java
src/test/java/neqsim/thermo/system/SystemPropertiesTest.java
src/test/java/neqsim/thermodynamicOperations/ThermodynamicOperationsTest.java

bugfix: named indexes was one off, NB! but not the calculated values.
refact: input pressure is specified in bara not in Pa

Bugfix systemproperties

---

src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorChartAlternativeMapLookup.java
src/main/java/neqsim/thermo/characterization/LumpingModel.java
src/main/java/neqsim/thermo/component/Component.java
src/main/java/neqsim/thermo/component/ComponentInterface.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/phase/PhaseBWRSEos.java
src/main/java/neqsim/thermo/phase/PhaseCSPsrkEos.java
src/main/java/neqsim/thermo/phase/PhaseElectrolyteCPA.java
src/main/java/neqsim/thermo/phase/PhaseElectrolyteCPAOld.java
src/main/java/neqsim/thermo/phase/PhaseEos.java
src/main/java/neqsim/thermo/phase/PhaseGE.java
src/main/java/neqsim/thermo/phase/PhaseInterface.java
src/main/java/neqsim/thermo/phase/PhaseModifiedFurstElectrolyteEos.java
src/main/java/neqsim/thermo/phase/PhaseModifiedFurstElectrolyteEosMod2004.java
src/main/java/neqsim/thermo/phase/PhasePCSAFT.java
src/main/java/neqsim/thermo/phase/PhasePCSAFTa.java
src/main/java/neqsim/thermo/phase/PhaseSrkCPA.java
src/main/java/neqsim/thermo/phase/PhaseSrkCPA_proceduralMatrices.java
src/main/java/neqsim/thermo/phase/PhaseSrkCPAojAlgo.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/thermodynamicOperations/ThermodynamicOperations.java
src/main/java/neqsim/util/exception/InvalidInputException.java
src/main/java/neqsim/util/exception/IsNaNException.java
src/main/java/neqsim/util/exception/NotInitializedException.java
src/main/java/neqsim/util/exception/ThermoException.java
src/main/java/neqsim/util/exception/TooManyIterationsException.java
src/test/java/neqsim/processSimulation/processEquipment/stream/StreamTest.java

refact: use new neqsim.exception constructors

feat: create neqsim.exception constructors with standardized error message

---

src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java

no need to keep a persistent copy of the pdf in systemthermo object

refact: simplified generatePDF and displayPDF

---

src/main/java/neqsim/processSimulation/processEquipment/TwoPortEquipment.java
src/main/java/neqsim/processSimulation/processEquipment/TwoPortInterface.java
src/main/java/neqsim/processSimulation/processEquipment/compressor/Compressor.java
src/main/java/neqsim/processSimulation/processEquipment/compressor/CompressorInterface.java
src/main/java/neqsim/processSimulation/processEquipment/expander/Expander.java
src/main/java/neqsim/processSimulation/processEquipment/expander/ExpanderInterface.java
src/main/java/neqsim/processSimulation/processEquipment/expander/ExpanderOld.java
src/main/java/neqsim/processSimulation/processEquipment/powerGeneration/GasTurbine.java
src/main/java/neqsim/processSimulation/processSystem/processModules/DPCUModule.java
src/main/java/neqsim/processSimulation/processSystem/processModules/MixerGasProcessingModule.java
src/main/java/neqsim/processSimulation/processSystem/processModules/PropaneCoolingModule.java
src/main/java/neqsim/processSimulation/processSystem/processModules/SeparationTrainModule.java
src/main/java/neqsim/processSimulation/processSystem/processModules/SeparationTrainModuleSimple.java
src/main/java/neqsim/processSimulation/util/monitor/CompressorResponse.java
src/test/java/neqsim/processSimulation/util/example/OffshoreProcess3.java
src/test/java/neqsim/processSimulation/util/example/OnshoreMEGprocess.java
src/test/java/neqsim/processSimulation/util/example/TestNeqsim.java
src/test/java/neqsim/processSimulation/util/example/TestSeparationTrain.java
src/test/java/neqsim/processSimulation/util/example/multiThreadTest.java
src/test/java/neqsim/processSimulation/util/example/propaneCoolingCycle.java
src/test/java/neqsim/processSimulation/util/example/propaneTwoStageCoolingCycle.java
src/test/java/neqsim/processSimulation/util/example/simpleTopSideProcess.java

New interfaces and new abstract classes to improve organization of process simulation units

refactor: Compressors have a single inlet and a single outlet and are twoports

---

src/main/java/neqsim/processSimulation/processEquipment/compressor/Compressor.java
src/main/java/neqsim/processSimulation/processEquipment/heatExchanger/HeatExchanger.java
src/main/java/neqsim/processSimulation/processEquipment/stream/Stream.java
src/main/java/neqsim/standards/gasQuality/Standard_ISO6976.java
src/main/java/neqsim/thermo/FluidCreator.java
src/main/java/neqsim/thermo/component/Component.java
src/main/java/neqsim/thermo/component/ComponentInterface.java
src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java

check that mvn uses java version 11 by running mvn -v

javadoc fixes for jdk11

---

src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/FluidSevereSlug.java
src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/Pipe.java
src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/SevereSlug.java
src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/SevereSlugAnalyser.java
src/main/java/neqsim/processSimulation/processEquipment/pipeline/AdiabaticTwoPhasePipe.java
src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/util/unit/PressureUnit.java
src/test/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/SevereSlugTest.java

AddedSevereSlug

---

src/main/java/neqsim/thermo/system/SystemThermo.java

Throw an exception if no component is found in neqsim database.
`throw new RuntimeException("No component with name: " + componentName + " in database");`

fix: change logger.info to exception if no component is found in neqsim database

---

src/main/java/neqsim/processSimulation/processSystem/ProcessModule.java

This pull request adds the `getUnit` and `copy` methods to the `ProcessModule` class. The `getUnit` method allows the user to retrieve a unit with a given name from the list of added unit operations and a list of added modules, while the copy method creates a deep copy of the `ProcessModule` instance.

feat: added getUnit and copy methods to ProcessModule

---

src/main/java/neqsim/fluidMechanics/flowSystem/twoPhaseFlowSystem/shipSystem/LNGship.java

Seems like the logic to select which ISO standard version to use was inverted. Suggested a fix

fix: use correct iso standard for lng ship calculations

---

src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java

Encountered a problem when running simulation twice:
pipe.run()
pipe.run()
Fix total length calc. (used length from previous run). 
Also introduce the result matrix in run function for (so that the results will not get into the same lists).

fix: Total length Pipe Beggs And Brills

---

src/main/java/neqsim/processSimulation/processEquipment/util/PressureDrop.java
src/test/java/neqsim/processSimulation/processEquipment/util/PressureDropTest.java

The pressure drop unit is used to simulate pressure drops in process plant (eg. pressure drop in pipings etc.). The pressure drop is simulated using a constant enthalpy flash.
Use:
PressureDrop dpGasStream1 = new PressureDrop("dp element 1", inletStream);
dpGasStream1.setPressureDrop(dp, "bara");
dpGasStream1.run();

added pressure drop element

---

src/main/java/neqsim/thermo/atomElement/Element.java
src/test/java/neqsim/thermo/atomElement/ElementTest.java

refact: Class Element, get all defined components.

---

src/main/java/neqsim/thermo/component/Component.java
src/main/java/neqsim/thermo/component/ComponentEos.java
src/main/java/neqsim/thermo/component/ComponentGE.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/phase/PhaseEos.java
src/main/java/neqsim/thermo/system/SystemEos.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/thermodynamicOperations/flashOps/Flash.java

Needed to expose these abstract classes to generate typing stubs for NeqSimPython

refactor: make abstract implementations of interfaces public

---

src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/phase/PhaseInterface.java
src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/test/java/neqsim/thermo/system/SystemPrEosTest.java

added use of unit when reading molar volume.

add use of unit for molar volume

---

SECURITY.md

Required to stay complient for public repos in Equinor. Used the Equinor [standard template](https://developer.equinor.com/governance/scm-policy/)

chore: add a security-policy

---

src/main/java/neqsim/PVTsimulation/simulation/SaturationPressure.java
src/main/java/neqsim/PVTsimulation/simulation/SaturationTemperature.java
src/test/java/neqsim/PVTsimulation/simulation/SaturationPressureTest.java
src/test/java/neqsim/PVTsimulation/simulation/SaturationTemperatureTest.java
src/test/java/neqsim/thermo/system/SystemUMRPRUMCEosNewTest.java

This PR add test to calculation of dew point pressure and dew point temperature and cricondenbar/cricondentherm conditions. It also fixes a bug in methods for direct calculation of dewpoint pressure/temperature that could make inaccurate calculations.

added test for umrpru

---

src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java

Fix factor S for multiphase flow when y value between 1 and 1.2

fix: pipe beggs and brills y factor

---

src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java
src/main/java/neqsim/util/exception/InvalidOutputException.java
src/test/java/neqsim/processSimulation/processEquipment/pipeline/BeggsAndBrillsPipeTest.java
src/test/java/neqsim/processSimulation/processEquipment/reservoir/WellFlowTest.java

- Change getSuperficialVelocity method to getInletSuperficialVelocity and getOutletSuperficialVelocity  
- Profiles start from segment 0 and length = 0 
- Add velocity to profile even if one phase 
- Add getNumberOfIncrements and getIncrementsProfile
- Change InvalidInputException to InvalidOutputException if calculated pressure is negative

fix: pipe BeggsAndBrills 

---

pomJava21.xml
pomJava8.xml

Snyk security update for log4j, needed to update in java 8 and java 21 poms aswell. 
Snyk does not support scanning multiple poms, so it is important to keep the dependencies synced to the one scanned with snyk. Should be fixed in the future

build(deps): sync log4j version in all poms

---

src/main/java/neqsim/processSimulation/processEquipment/pipeline/PipeBeggsAndBrills.java
src/test/java/neqsim/processSimulation/processEquipment/pipeline/BeggsAndBrillsPipeTest.java
src/test/java/neqsim/processSimulation/processEquipment/pipeline/PipelineTest.java
src/test/java/neqsim/processSimulation/processEquipment/util/AdjusterTest.java

fix: pipeBeggsAndBrills

---

src/main/java/neqsim/processSimulation/processSystem/ProcessModule.java

Fix typo as mentioned by @asmfstatoil. Thanks !

fix: typo in ProcessModule

---

src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java

remove deprecated function IsPhase

refact: system addcomponent and display

---

src/main/java/neqsim/chemicalReactions/chemicalEquilibriaum/ChemEq.java
src/main/java/neqsim/fluidMechanics/flowNode/FlowNode.java
src/main/java/neqsim/fluidMechanics/flowNode/fluidBoundary/heatMassTransferCalc/FluidBoundary.java
src/main/java/neqsim/physicalProperties/physicalPropertyMethods/liquidPhysicalProperties/viscosity/Viscosity.java
src/main/java/neqsim/processSimulation/measurementDevice/HydrateEquilibriumTemperatureAnalyser.java
src/main/java/neqsim/processSimulation/mechanicalDesign/MechanicalDesign.java
src/main/java/neqsim/standards/Standard.java
src/main/java/neqsim/standards/gasQuality/Draft_GERG2004.java
src/main/java/neqsim/standards/gasQuality/Standard_ISO6976.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/thermodynamicOperations/ThermodynamicOperations.java
src/test/java/neqsim/fluidMechanics/flowNode/twoPhaseNode/twoPhasePipeFlowNode/StratifiedFlowNodeTest.java
src/test/java/neqsim/processSimulation/processSystem/ProcessSystemTest.java
src/test/java/neqsim/standards/gasQuality/Standard_ISO15403Test.java
src/test/java/neqsim/standards/gasQuality/Standard_ISO6578Test.java
src/test/java/neqsim/standards/gasQuality/Standard_ISO6976Test.java
src/test/java/neqsim/standards/gasQuality/Standard_ISO6976_2016_Test.java
src/test/java/neqsim/standards/salesContract/BaseContractTest.java
src/test/java/neqsim/thermo/system/SystemThermoTest.java
src/test/java/neqsim/thermodynamicOperations/ThermodynamicOperationsTest.java

fix: some cases where display methods failed

---

.github/workflows/verify_build.yml
src/main/java/neqsim/thermo/component/ComponentInterface.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/phase/PhaseInterface.java
src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/test/java/neqsim/thermo/phase/PhaseSrkEosTest.java

feat: new function Phase.getComponentNames

feat: Phase.hasComponent check against normalized name

---

src/main/java/neqsim/thermo/component/ComponentSolid.java
src/main/java/neqsim/thermo/phase/PhasePureComponentSolid.java
src/main/java/neqsim/thermo/phase/PhaseSolid.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/util/database/NeqSimDataBase.java
src/test/java/neqsim/thermodynamicOperations/flashOps/TPsolidFlash.java

fix solid calcs

---

src/main/java/neqsim/Units.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/phase/PhaseInterface.java
src/main/java/neqsim/thermo/system/SystemInterface.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/util/unit/PressureUnit.java
src/main/java/neqsim/util/unit/TemperatureUnit.java
src/test/java/neqsim/thermo/system/SystemPrEoSTest.java
src/test/java/neqsim/util/unit/PressureUnitTest.java

Improve unit handeling by adding a unit class.

Add more units

---

pom.xml
pomJava21.xml
pomJava8.xml
src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentBaseClass.java
src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentInterface.java
src/main/java/neqsim/processSimulation/processEquipment/TwoPortEquipment.java
src/main/java/neqsim/processSimulation/processEquipment/compressor/Compressor.java
src/main/java/neqsim/processSimulation/processEquipment/heatExchanger/Cooler.java
src/main/java/neqsim/processSimulation/processEquipment/heatExchanger/Heater.java
src/main/java/neqsim/processSimulation/processEquipment/separator/Separator.java
src/main/java/neqsim/processSimulation/processEquipment/separator/ThreePhaseSeparator.java
src/main/java/neqsim/processSimulation/processEquipment/stream/Stream.java
src/main/java/neqsim/processSimulation/processEquipment/valve/ThrottlingValve.java
src/main/java/neqsim/processSimulation/processSystem/ProcessModule.java
src/main/java/neqsim/processSimulation/processSystem/ProcessModuleBaseClass.java
src/main/java/neqsim/processSimulation/processSystem/ProcessSystem.java
src/main/java/neqsim/processSimulation/util/monitor/StreamResponse.java
src/main/java/neqsim/processSimulation/util/monitor/ValveResponse.java
src/main/java/neqsim/processSimulation/util/report/Report.java
src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/util/unit/Units.java
src/test/java/neqsim/processSimulation/util/report/ReportTest.java

Implementation of reporting results from process simulation in json format. Also further work on handling unit formats.

first implementation of reporting of process

---

src/main/java/neqsim/processSimulation/SimulationInterface.java
src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentBaseClass.java
src/main/java/neqsim/processSimulation/processEquipment/ProcessEquipmentInterface.java
src/main/java/neqsim/processSimulation/processSystem/ProcessModule.java
src/main/java/neqsim/processSimulation/processSystem/ProcessModuleBaseClass.java
src/main/java/neqsim/processSimulation/processSystem/ProcessSystem.java
src/main/java/neqsim/processSimulation/util/monitor/StreamResponse.java
src/main/java/neqsim/processSimulation/util/monitor/Value.java
src/main/java/neqsim/processSimulation/util/report/Report.java

Further improvement of reporting process simulation results as json format.

added Value as response

---

src/main/java/neqsim/processSimulation/measurementDevice/FlowInducedVibrationAnalyser.java
src/main/java/neqsim/processSimulation/measurementDevice/simpleFlowRegime/Pipe.java
src/main/java/neqsim/processSimulation/processEquipment/util/FlowRateAdjuster.java

fix: bug with str units

---

src/main/java/neqsim/processSimulation/processEquipment/util/FlowRateAdjuster.java
src/main/java/neqsim/thermo/component/Component.java

1. Update flow rate adjuster to accept 2 phases only. 
2. If the change request of a component dn is very small < 1e-12 and causes error (I got errors in splitter that component C12 1e-25 and change request was -2e-25 ..), set change request to 0 in this case.

feat: update flow rate adjuster and fix negative change request if value is small (<1e-12)

---

src/main/java/neqsim/processSimulation/processEquipment/heatExchanger/HeatExchanger.java

When run HEX with UA value equal to 0, I got duty which was > 0 (and temperature change). This pull request fixes the problem by firstly running all the input streams

fix: Heat Exchangers wrong Enthalpy calculations

---

src/main/java/neqsim/process/equipment/compressor/Compressor.java
src/main/java/neqsim/process/equipment/expander/Expander.java
src/main/java/neqsim/process/equipment/stream/EnergyStream.java
src/test/java/neqsim/process/equipment/compressor/CompressorTest.java

option to add energy stream to compressor and expanders

added option to add energy stream

---

src/main/java/neqsim/process/equipment/heatexchanger/MultiStreamHeatExchanger.java
src/test/java/neqsim/process/equipment/heatexchanger/MultiStreamHeatExchangerTest.java

makes it possible to specify overall UA value of a multi stream HX. Method is not optimized for seed and ropbustnes, but works for test case.
src/test/java/neqsim/process/equipment/heatexchanger/MultiStreamHeatExchangerTest.java

specify UA for multi stream HX

---

src/main/java/neqsim/thermo/phase/Phase.java
src/main/java/neqsim/thermo/system/SystemThermo.java
src/main/java/neqsim/thermodynamicoperations/flashops/RachfordRice.java
src/main/java/neqsim/thermodynamicoperations/flashops/SolidFlash.java
src/main/java/neqsim/thermodynamicoperations/flashops/SolidFlash1.java
src/main/java/neqsim/thermodynamicoperations/flashops/TPflash.java
src/main/java/neqsim/thermodynamicoperations/flashops/TPmultiflash.java
src/main/java/neqsim/thermodynamicoperations/flashops/dTPflash.java

using neqsim.thermo.ThermodynamicModelSettings.phaseFractionMinimumLimit

feat: more robust setting of beta

---

src/main/java/neqsim/process/equipment/util/StreamTransition.java
src/test/java/neqsim/process/equipment/util/StreamTransitionTest.java

This class provides functionality for transferring fluid properties between streams with
potentially different thermodynamic models and component sets. It enables seamless transitions
between process units that may use different thermodynamic frameworks.
Added class-level and method-level documentation to StreamTransition, including a clear TODO noting that only TP-based transitions are currently supported and PH-based transitions could be added in the future.

improved functionality of stream transition
